[platformio]
default_envs = native

[env:native]
platform = native
test_framework = unity
build_flags = -std=c++17 -Ilib/telemetrie

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_flags = -std=c++17 -Ilib/telemetrie
lib_deps =
    jgromes/RadioLib
